
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyveocbkzybboaqythvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5dmVvY2JrenliYm9hcXl0aHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNjQ3NTUsImV4cCI6MjA1Nzg0MDc1NX0.OoayW-RJ0sdHYL7Mki_RWqK9dyQQREp8a3WfIK9OjNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
